project:
  type: website
  output-dir: _site

website:
  title: "Sarasota County Race Data"
  navbar:
    left:
      - text: Home
        href: index.qmd

format:
  html:
    theme: journal
    toc: true
    code-fold: true
    embed-resources: true
